# Generated by Django 5.0 on 2023-12-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('train_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('s1', models.CharField(max_length=50)),
                ('s2', models.CharField(max_length=50)),
                ('seats', models.IntegerField(max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=20)),
            ],
        ),
    ]
