# Generated by Django 5.0 on 2023-12-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='date',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
