# Generated by Django 5.0 on 2023-12-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_passengers_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
