# Generated by Django 5.0 on 2023-12-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_train_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
