# Generated by Django 5.0 on 2023-12-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_train_train_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='time',
            field=models.DateField(max_length=20),
        ),
    ]
