# Generated by Django 5.0 on 2023-12-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_alter_train_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='time',
            field=models.TimeField(max_length=20),
        ),
    ]
