# Generated by Django 5.0 on 2023-12-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_info_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='s_1',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='s_2',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
