# Generated by Django 5.0 on 2023-12-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_info_s_1_info_s_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='train_name',
            new_name='train_id',
        ),
        migrations.AddField(
            model_name='passengers',
            name='age',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengers',
            name='email',
            field=models.CharField(default='o', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengers',
            name='gender',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passengers',
            name='meal',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
