# Generated by Django 5.0 on 2023-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_rename_train_name_passengers_train_id_passengers_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='mobile',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
