# Generated by Django 5.0 on 2023-12-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_alter_passengers_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='unique_id',
            field=models.CharField(default=True, max_length=34),
            preserve_default=False,
        ),
    ]
