# Generated by Django 5.0 on 2023-12-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0013_passengers_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='fare',
            new_name='fare1',
        ),
        migrations.AddField(
            model_name='train',
            name='fare2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='fare3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='fareg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='train',
            name='fares',
            field=models.IntegerField(default=0),
        ),
    ]
