# Generated by Django 5.0 on 2024-01-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0016_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='seats',
            new_name='seats1',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='seats',
            new_name='seats1',
        ),
        migrations.AddField(
            model_name='info',
            name='seats2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='seats3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='seatsg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='seatss',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='seats2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='seats3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='seatsg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='seatss',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
