# Generated by Django 5.0 on 2024-01-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0017_rename_seats_info_seats1_rename_seats_train_seats1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='journeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=50)),
                ('journey', models.CharField(max_length=50)),
            ],
        ),
    ]
