# Generated by Django 5.0 on 2024-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0021_remove_info_s_2_remove_train_s2_alter_info_s_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='clas',
            field=models.CharField(default=True, max_length=78),
            preserve_default=False,
        ),
    ]
