# Generated by Django 5.0 on 2024-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0022_passengers_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
