# Generated by Django 5.0 on 2024-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0023_passengers_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='time',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
