# Generated by Django 5.0 on 2024-01-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0024_info_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeys',
            name='date',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
