# Generated by Django 5.0 on 2024-01-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0025_journeys_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeys',
            name='time',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
