# Generated by Django 5.0 on 2024-01-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0028_alter_train_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeys',
            name='user',
            field=models.CharField(default=True, max_length=70),
            preserve_default=False,
        ),
    ]
